services:
    lr94.lc.listener:
        class: lr94\lc\event\main_listener
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '@request'
            - '%core.table_prefix%'
        tags:
            - { name: event.listener }
